
volumes:
  pg_db:

services:
  poll_db:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_DB=poll_db
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=myuser
    volumes:
      - pg_db:/var/lib/postgresql/data
    ports:
      - '127.0.0.1:5432:5432'
  app:
    restart: always
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - poll_db
    environment:
      SPRING_DATASOURCE_URL: 'jdbc:postgresql://poll_db:5432/poll_db'
      JAVA_OPTS: '-Xmx512m'